### ISSUE TITLE
Some feedbacks, and problems about disabling HUD features, and alignments

### ISSUE THREAD

**Issue by borzaka** [lexogrine/csgo-react-hud#13]
Hi guys! First of all, really a great work!

I am using the free version, and I tried it out on some official Matchmaking live matches.

I have couple of feedbacks/problems:
1) I have disabled the custom radar in the HUD settings, but it's still shown. I know I can hide it with CTRL+B, but it would be nice if I don't enable, it wouldn't even shown up.
2) I have also disabled (and not used) the custom killfeed, but the "x planted the bomb" / "y defused the bomb" messages are still shown, and interferes with the native game killfeed. Maybe this is also a problem with the custom killfeed as well? How could I disable these custom messages?
![image](https://user-images.githubusercontent.com/1230402/96035413-4c532280-0e63-11eb-8983-fd01665ae4bc.png)
3) Can't hide only the extra boxes (left and right display boxes), because if I hide them, it also hides the utility level boxes and other stats boxes (loss bonus, team money, equipment value), but I want them.
4) If you don't setup a Match, "Best of 0" will be shown under the timer. It would be nice, to hide that row, if there is no Match setup. Or a no Match would be atomically a BO1, but there are also some unnecessary design changes even with BO1, which is not needed; black bar under map, 1-1 win indicator under teamname.
![image](https://user-images.githubusercontent.com/1230402/96034337-abb03300-0e61-11eb-9850-198cd30d4a0b.png)
5) The win panel is sometimes overlapping with the native killfeed. Maybe this also a problem with the custom killfeed?
![image](https://user-images.githubusercontent.com/1230402/96035026-b28b7580-0e62-11eb-880f-e7f91e19b4cd.png)
6) The radar (and the custom killfeed) is misaligned with the rest of the HUD elements:
![image](https://user-images.githubusercontent.com/1230402/96032690-5410c800-0e5f-11eb-9e1e-fd1f5549e210.png)
7) And also dead players on the custom map doesn't look like X's, as seen in other screenshots from boltobserv. And overlapping with live players.

**Comment by osztenkurden** [comment]
1) and 2) are happening because toggle menu in the Manager are not for HUD settings - they are for creating the correct config line that is needed to be executed in the CS:GO. 2) can be removed from the HUD by removing from the src/HUD/Killfeed/Killfeed.tsx lines:
`        GSI.on("bombPlant", player => {
            this.addBombEvent(player, 'plant');
        })
        GSI.on("bombDefuse", player => {
            this.addBombEvent(player, 'defuse');
        })
`
3) We are thinking about this, but you can do it right now if you now enough about panel.json API, for now it is not a priority.
4) Fixed in the 1.6.0 release
5) This will be tackled soon
6) Fixed in the 1.6.0 release
7) That's true - we will be redesigning radar soon

**Comment by badguycsgo** [comment]
I can't find the Killfeed.tsx file, can you tell me where that file is?
