### ISSUE TITLE
Team-names and scores are not switched after first half

### ISSUE THREAD

**Issue by badguycsgo** [lexogrine/csgo-react-hud#21]
Hi guys, first I want to say that I am really appreciated for your amazing work!

I have used your HUD for my school tournament and it is very beautiful. But i have noticed that after first half, the team-names displayed on top of the HUD were not switch, and maybe so does the score as well, I didn't remember specifically. And then i had to press on the Reversed Side button, not by 1 but 2 times in order to make things back to normal.

Can you please fix that problem by adding a method that automatically switch team-names and scores? Thank you very much.

**Comment by osztenkurden** [comment]
We are not supporting automatic switch after first half. It is possible to reverse them by Alt+R
