### ISSUE TITLE
HUD "lagging" when switching player

### ISSUE THREAD

**Issue by killshotzz** [lexogrine/csgo-react-hud#37]
Hello Lexogrine!

We are a small esports association, in a small town, that uses Lexogrine and the React HUD to stream our matches.

So far we have been loving the features, but in the last 2 updates, there have been various problems for us.

1. We have had problems with the HUD snapping to the game in multiple instances. We have fixed it sometimes by closing steam, but the error occurs again in some time.
2. In the newest update, we have had problems with "lag" when switching between players, and we have so far not found a fix to this. It takes a lot of time to load the correct player, and we have tried multiple things to fix this (within our limit of knowledge of course).

Have you ever tried or heard about this problem, or knows how to fix it? We can provide a video of it if needed.

Thank you for a great program and for the help in advance!

**Comment by osztenkurden** [comment]
Hi!
I'm not sure what you mean by HUD snapping to the game in 1). Do you mean HUD being below the CS:GO?
About 2) - which LHM and HUD version do you use? And video would be very good to see whats happening directly :)

**Comment by ksgoescoding** [comment]
Hi!

1. Yes the HUD is below CS:GO and cannot be snapped back onto the game before we close steam and the HUD itself.

2. The video is shown down below in the link. We have tried both on downloading a demo, playing a GOTV demo and streaming a live match. None worked. I have figured out, that it is the boxes (where you can write stuff on top off the player names and utility etc) that makes the bug.

We tried to delete everything and that worked. But as soon as we entered 1 letter, it was lagging again.

Link to the video: https://streamable.com/80k2bc

Thank you again!

**Comment by ksgoescoding** [comment]
> Hi!
> 
> 1. Yes the HUD is below CS:GO and cannot be snapped back onto the game before we close steam and the HUD itself.
> 2. The video is shown down below in the link. We have tried both on downloading a demo, playing a GOTV demo and streaming a live match. None worked. I have figured out, that it is the boxes (where you can write stuff on top off the player names and utility etc) that makes the bug.
> 
> We tried to delete everything and that worked. But as soon as we entered 1 letter, it was lagging again.
> 
> Link to the video: https://streamable.com/80k2bc
> 
> Thank you again!

We also now just discovered, that it is the pictures you can add to those boxes that makes it lag.

**Comment by osztenkurden** [comment]
True, it does that, we are working on the fix - usually its because the images are too big. The view is small, so try with images at most 200x200. It shouldnt lag then

**Comment by osztenkurden** [comment]
Update on the issue: Lexogrine HUD Manager 2.0 will feature endpoint that will fix the issue. It will require small change in the HUDs though.
