### ISSUE TITLE
Pause info

### ISSUE THREAD

**Issue by GoRnoStayStandin** [lexogrine/csgo-react-hud#4]
Your HUD is realy greate, but it would be cool if you add information about pause. 
I was testing your HUD in demo and mutchmaking spectating and there are no information which team takes pause. I think, that it's easy for you to add this think :)

**Comment by borzaka** [comment]
Probably something like this would be nice:
![image](https://user-images.githubusercontent.com/1230402/99594731-df97ee80-29f3-11eb-879d-6637ea94e623.png)

And you could toggle, and the left/right side would disappear during showing this round and player info.
