### ISSUE TITLE
Bind for players & match overview

### ISSUE THREAD

**Issue by GoRnoStayStandin** [lexogrine/csgo-react-hud#7]
Is there any binds for toggle on and toggle off show player preview/show upcoming match?

It's going to be hard to toggle it with minimize the game...

**Comment by osztenkurden** [comment]
@GoRnoStayStandin I will add it soon - just remember you can technically access HUD Manager panel on the local network from different PC and toggle stuff from there

**Comment by DenVilk** [comment]
@osztenkurden , how can I toggle it? I can't to find documentation about it
